profile: cover.out

threshold:
  file: 0
  package: 0
  total: 0

exclude:
  paths:
    - ^internal/models
    - ^internal/repository
    - ^cmd/
    - ^db/
    - ^docs/
    - \.pb\.go$
    - ^vendor/

override: []
