// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/categories": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all product categories ordered by ID. Requires the ayurami-admin or ayurami-salesperson role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "categories"
                ],
                "summary": "List product categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Category"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/email-receipts": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves stored bank receipts, optionally filtered by a received_at date range. Requires the ayurami-admin or ayurami-salesperson role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email-receipts"
                ],
                "summary": "List stored email receipts",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD, inclusive)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, inclusive)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.EmailReceipt"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid date",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/email-receipts/summary": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Calculates total revenue, transaction counts, average ticket, period-over-period growth, and daily timeline buckets from email receipts. Requires ayurami-admin or ayurami-salesperson role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email-receipts"
                ],
                "summary": "Get revenue summary and analytics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Start date (YYYY-MM-DD, inclusive)",
                        "name": "from",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (YYYY-MM-DD, inclusive)",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.RevenueSummary"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid date or date range",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/email-receipts/sync": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Reads receipt registers from the configured Google Sheets document in chunks and stores new sale details. Requires the ayurami-admin role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email-receipts"
                ],
                "summary": "Sync bank receipts from Google Sheets",
                "parameters": [
                    {
                        "description": "Optional date range (from/to as YYYY-MM-DD)",
                        "name": "range",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/service.EmailReceiptSyncRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SyncResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid JSON payload or date range",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/products": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all products ordered alphabetically by name. Requires the ayurami-admin or ayurami-salesperson role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "List products",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Product"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new product in the catalog and initializes its inventory to zero. Requires the ayurami-admin role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Create a new product",
                "parameters": [
                    {
                        "description": "Product Creation Payload",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid JSON payload or missing name",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/products/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves detailed information of a single product. Requires the ayurami-admin or ayurami-salesperson role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Get a product by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Product"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid product ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates an existing product's fields. Requires the ayurami-admin role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Update a product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Product Update Payload",
                        "name": "product",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.ProductRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid ID or invalid JSON payload or missing name",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a product along with all associated inventory, recipe entries, and allowed additions. Requires the ayurami-admin role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "products"
                ],
                "summary": "Delete a product",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Product ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Product not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/sales": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers a new sale, deducts product or recipe ingredient inventory, and records details. Requires the ayurami-admin or ayurami-salesperson role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sales"
                ],
                "summary": "Create a new sale",
                "parameters": [
                    {
                        "description": "Sale Creation Payload",
                        "name": "sale",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SaleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.SaleResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid JSON payload or sale must have at least one item",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/suppliers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all registered suppliers with optional search filtering by company name, tax ID, or contact. Requires the ayurami-admin or ayurami-salesperson role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "List suppliers",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Search filter query",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Supplier"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Registers a new goods or ingredients provider. Requires the ayurami-admin role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Create a new supplier",
                "parameters": [
                    {
                        "description": "Supplier Creation Payload",
                        "name": "supplier",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SupplierRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid payload or missing fields",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict: tax ID already registered",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/suppliers/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves detailed information of a single supplier. Requires the ayurami-admin or ayurami-salesperson role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Get a supplier by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Supplier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Supplier"
                        }
                    },
                    "400": {
                        "description": "Invalid supplier ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Supplier not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Modifies an existing supplier's details. Requires the ayurami-admin role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Update a supplier",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Supplier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Supplier Update Payload",
                        "name": "supplier",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.SupplierRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid payload or missing fields",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Supplier not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict: tax ID already registered",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a supplier by ID if they have no associated purchases. Requires the ayurami-admin role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "suppliers"
                ],
                "summary": "Delete a supplier",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Supplier ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid supplier ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Supplier not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "409": {
                        "description": "Conflict: cannot delete supplier with associated purchases",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/units-of-measure": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all available units of measure ordered by name. Requires the ayurami-admin or ayurami-salesperson role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "units-of-measure"
                ],
                "summary": "List units of measure",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.UnitOfMeasure"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves all registered users ordered alphabetically by name. Requires the ayurami-admin role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Creates a new system user (admin or salesperson) with a secure hashed password. Requires the ayurami-admin role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "User Creation Payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieves detailed user profile information. Requires the ayurami-admin role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get user by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Updates a user's role, password, fullName, or status. Requires the ayurami-admin role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User Update Payload",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Deletes a user from the system. Requires the ayurami-admin role.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete user",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "User not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/hello": {
            "get": {
                "description": "Returns a simple web page with the centered logo and \"hecho en Colombia\" footer.",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Hello Endpoint Web Page",
                "responses": {
                    "200": {
                        "description": "HTML page",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/hello/logo.png": {
            "get": {
                "description": "Returns the embedded Ayurami logo image bytes.",
                "produces": [
                    "image/png"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Logo image",
                "responses": {
                    "200": {
                        "description": "logo image bytes",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authenticates a user and returns a JWT token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "User Login",
                "parameters": [
                    {
                        "description": "User Credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request: invalid JSON payload or missing username",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: invalid credentials",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "403": {
                        "description": "Forbidden: account is inactive",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/refresh": {
            "post": {
                "description": "Generates a new token pair using a valid refresh token.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Refresh JWT Token",
                "parameters": [
                    {
                        "description": "Refresh Token",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: invalid refresh token",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/status": {
            "get": {
                "description": "Checks if the API is running and verifies connection to the database.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "System Health Status",
                "responses": {
                    "200": {
                        "description": "Status OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.LoginRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "handlers.LoginResponse": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "handlers.MessageResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handlers.RefreshRequest": {
            "type": "object",
            "properties": {
                "refreshToken": {
                    "type": "string"
                }
            }
        },
        "handlers.SaleResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "saleId": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "handlers.SyncResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "result": {
                    "$ref": "#/definitions/service.SyncResult"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.Category": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt is the timestamp when the category was created (Spanish: Creado En).",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier (Spanish: ID).",
                    "type": "integer"
                },
                "name": {
                    "description": "Name is the category name (Spanish: Nombre).",
                    "type": "string"
                }
            }
        },
        "models.DailyRevenueBucket": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "number"
                },
                "count": {
                    "type": "integer"
                },
                "date": {
                    "type": "string"
                }
            }
        },
        "models.EmailReceipt": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Amount is the payment amount (Spanish: Monto).",
                    "type": "number"
                },
                "bank": {
                    "description": "Bank is the originating bank (Spanish: Banco).",
                    "type": "string"
                },
                "createdAt": {
                    "description": "CreatedAt is the ingestion timestamp (Spanish: Creado En).",
                    "type": "string"
                },
                "currency": {
                    "description": "Currency is the ISO currency code (Spanish: Moneda).",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier (Spanish: ID).",
                    "type": "integer"
                },
                "messageId": {
                    "description": "MessageID is the source email message id; unique and used for idempotent ingestion (Spanish: ID Mensaje).",
                    "type": "string"
                },
                "parseError": {
                    "description": "ParseError holds the parsing failure message when Status is error (Spanish: Error de Parseo).",
                    "type": "string"
                },
                "payer": {
                    "description": "Payer is the person/entity that paid (Spanish: Pagador).",
                    "type": "string"
                },
                "paymentMethod": {
                    "description": "PaymentMethod is the payment method label (e.g. QR Negocios Bre-B) (Spanish: Método de Pago).",
                    "type": "string"
                },
                "receivedAt": {
                    "description": "ReceivedAt is when the inbox received the email (Spanish: Recibido En).",
                    "type": "string"
                },
                "reference": {
                    "description": "Reference is the bank reference code (Spanish: Referencia).",
                    "type": "string"
                },
                "sender": {
                    "description": "Sender is the email sender address (Spanish: Remitente).",
                    "type": "string"
                },
                "status": {
                    "description": "Status is the ingestion status: imported or error (Spanish: Estado).",
                    "type": "string"
                },
                "subject": {
                    "description": "Subject is the email subject line (Spanish: Asunto).",
                    "type": "string"
                },
                "transactionDate": {
                    "description": "TransactionDate is the date/time of the payment as reported in the receipt body (Spanish: Fecha de Transacción).",
                    "type": "string"
                },
                "transactionNumber": {
                    "description": "TransactionNumber is the unique transaction id from the bank (Spanish: Número de Transacción).",
                    "type": "string"
                }
            }
        },
        "models.Product": {
            "type": "object",
            "properties": {
                "averageCost": {
                    "description": "AverageCost is the dynamic weighted cost from purchases (Spanish: Costo Promedio).",
                    "type": "number"
                },
                "categoryId": {
                    "description": "CategoryID is the reference ID of the category (Spanish: ID Categoría).",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "CreatedAt is the creation timestamp (Spanish: Creado En).",
                    "type": "string"
                },
                "description": {
                    "description": "Description is the optional product description (Spanish: Descripción).",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier (Spanish: ID).",
                    "type": "integer"
                },
                "isForSale": {
                    "description": "IsForSale defines if it can be sold in the POS (Spanish: Es Para Venta).",
                    "type": "boolean"
                },
                "name": {
                    "description": "Name is the commercial name (Spanish: Nombre).",
                    "type": "string"
                },
                "requiresRecipe": {
                    "description": "RequiresRecipe defines if it deducts child recipe items upon sale (Spanish: Requiere Receta).",
                    "type": "boolean"
                },
                "sellPrice": {
                    "description": "SellPrice is the price for customers, can be 0 for pure ingredients (Spanish: Precio de Venta).",
                    "type": "number"
                },
                "unitOfMeasureId": {
                    "description": "UnitOfMeasureID is the reference ID of the unit of measure (Spanish: ID Unidad de Medida).",
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "UpdatedAt is the last modification timestamp (Spanish: Actualizado En).",
                    "type": "string"
                }
            }
        },
        "models.RevenueSummary": {
            "type": "object",
            "properties": {
                "averageTicket": {
                    "type": "number"
                },
                "currency": {
                    "type": "string"
                },
                "growthPercentage": {
                    "type": "number"
                },
                "previousPeriodRevenue": {
                    "type": "number"
                },
                "timeline": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.DailyRevenueBucket"
                    }
                },
                "totalRevenue": {
                    "type": "number"
                },
                "transactionCount": {
                    "type": "integer"
                }
            }
        },
        "models.Supplier": {
            "type": "object",
            "properties": {
                "companyName": {
                    "description": "CompanyName is the legal name of the business (Spanish: Razón Social).",
                    "type": "string"
                },
                "contactName": {
                    "description": "ContactName is the provider contact representative (Spanish: Nombre de Contacto).",
                    "type": "string"
                },
                "createdAt": {
                    "description": "CreatedAt is the timestamp when the supplier was registered (Spanish: Creado En).",
                    "type": "string"
                },
                "email": {
                    "description": "Email is the contact email address (Spanish: Correo Electrónico).",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier (Spanish: ID).",
                    "type": "integer"
                },
                "phone": {
                    "description": "Phone is the contact number (Spanish: Teléfono).",
                    "type": "string"
                },
                "taxId": {
                    "description": "TaxID is the tax identifier (e.g. NIT/Cédula) (Spanish: NIT o Cédula).",
                    "type": "string"
                }
            }
        },
        "models.UnitOfMeasure": {
            "type": "object",
            "properties": {
                "abbreviation": {
                    "description": "Abbreviation is the short code representing the unit (Spanish: Abreviatura).",
                    "type": "string"
                },
                "createdAt": {
                    "description": "CreatedAt is the timestamp when the unit was created (Spanish: Creado En).",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier (Spanish: ID).",
                    "type": "integer"
                },
                "name": {
                    "description": "Name is the name of the unit (Spanish: Nombre).",
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "CreatedAt is the registration timestamp (Spanish: Creado En).",
                    "type": "string"
                },
                "fullName": {
                    "description": "FullName is the operator's real name (Spanish: Nombre Completo).",
                    "type": "string"
                },
                "id": {
                    "description": "ID is the unique identifier (Spanish: ID).",
                    "type": "integer"
                },
                "isActive": {
                    "description": "IsActive defines if the user account is enabled (Spanish: Activo).",
                    "type": "boolean"
                },
                "role": {
                    "description": "Role is the authorization role (e.g. Administrator, Cajero) (Spanish: Rol).",
                    "type": "string"
                },
                "username": {
                    "description": "Username is the login identifier (Spanish: Nombre de Usuario).",
                    "type": "string"
                }
            }
        },
        "service.EmailReceiptSyncRequest": {
            "type": "object",
            "properties": {
                "from": {
                    "type": "string"
                },
                "to": {
                    "type": "string"
                }
            }
        },
        "service.ProductRequest": {
            "type": "object",
            "properties": {
                "averageCost": {
                    "type": "number"
                },
                "categoryId": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "isForSale": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "requiresRecipe": {
                    "type": "boolean"
                },
                "sellPrice": {
                    "type": "number"
                },
                "unitOfMeasureId": {
                    "type": "integer"
                }
            }
        },
        "service.SaleItemRequest": {
            "type": "object",
            "properties": {
                "productId": {
                    "type": "integer"
                },
                "quantity": {
                    "type": "number"
                }
            }
        },
        "service.SaleRequest": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.SaleItemRequest"
                    }
                },
                "paymentMethod": {
                    "type": "string"
                },
                "totalAmount": {
                    "type": "number"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "service.SupplierRequest": {
            "type": "object",
            "properties": {
                "companyName": {
                    "type": "string"
                },
                "contactName": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                },
                "taxId": {
                    "type": "string"
                }
            }
        },
        "service.SyncResult": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "integer"
                },
                "fetched": {
                    "type": "integer"
                },
                "imported": {
                    "type": "integer"
                },
                "skipped": {
                    "type": "integer"
                }
            }
        },
        "service.UserRequest": {
            "type": "object",
            "properties": {
                "fullName": {
                    "type": "string"
                },
                "isActive": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer \" followed by the JWT obtained from POST /login.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Banana Project Go REST API",
	Description:      "This is the API server for Banana Project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
